name: tripusfrontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  mapbox_search: ^3.2.0
  get_storage: 2.1.1
  file_picker: 5.3.3
  flutter: 
    sdk: flutter
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_easyloading: ^3.0.5
  intl: ^0.18.0
  timeago: ^3.5.0
  skeletons: ^0.0.3
  calendar_date_picker2: ^0.5.2
  currency_text_input_formatter: ^2.1.10
  dotted_dashed_line: ^0.0.3
  device_preview: ^1.1.0
  nanoid: ^1.0.0
  pull_to_refresh: ^2.0.0
  clipboard: ^0.1.3
  card_swiper: ^3.0.1
  appinio_swiper: ^2.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/payment/
  uses-material-design: true

